# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

hosts = {
    "tomcat-vm0" => "192.168.33.10",
}

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  hosts.each do |name, ip|
    config.vm.define name do |machine|
      machine.vm.box = "chef/centos-6.5"
      machine.vm.hostname = "%s.example.com" % name
      machine.vm.network :private_network, ip: ip
      machine.vm.network :forwarded_port, guest: 8080, host: 8080
      machine.vm.provider "virtualbox" do |v|
        v.name = name
        v.customize ["modifyvm", :id, "--memory", 2048]
      end
    end
  end
end
