---
- name: Check for newrelic_license_key
  fail:
    msg: "newrelic_license_key has not been defined"
  when: newrelic_license_key|default(False) == False

- name: Set newrelic_loaded_os_family
  set_fact:
    newrelic_loaded_os_family: "{{ ansible_os_family }}"

- name: Add the New Relic repository key
  copy:
    src: RPM-GPG-KEY-NewRelic
    dest: /etc/pki/rpm-gpg
    owner: root
    group: root
    mode: 0644

- name: Add the New Relic repository file
  copy:
    src: newrelic.repo
    dest: /etc/yum.repos.d/newrelic.repo
    owner: root
    group: root
    mode: 0644

- name: Install the New Relic Sysmond
  yum:
    name: newrelic-sysmond
    state: latest
  notify:
    - Restart New Relic

- name: Configure New Relic Sysmond
  template:
    src: nrsysmond.cfg.j2
    dest: /etc/newrelic/nrsysmond.cfg
    group: newrelic
    owner: root
    mode: 0640
  notify:
    - Restart New Relic

- name: Ensure New Relic Sysmond is started and enabled
  service:
    name: newrelic-sysmond
    state: started
    enabled: yes
